---

name: Linux GCC

on: [push, pull_request, workflow_dispatch]

jobs:
  linux_gcc:
    uses: ./.github/workflows/CI-launcher.yml
    with:
      min_runner: ubuntu-24.04
      min_toolchain_id: linux-gcc-13
      latest_runner: ubuntu-24.04
      latest_toolchain_id: linux-gcc-15
