---

name: Linux Clang

on: [push, pull_request, workflow_dispatch]

jobs:
  linux_clang17:
    uses: ./.github/workflows/CI-common.yml
    with:
      runner: ubuntu-24.04
      toolchain_id: linux-clang-17

  linux_clang21:
    uses: ./.github/workflows/CI-common.yml
    with:
      runner: ubuntu-24.04
      toolchain_id: linux-clang-21
