---
name: CI workflow

on:
  workflow_call:
    inputs:
      runner:
        type: string
        description: 'The github runner for the workflow'
        required: true
      toolchain_id:
        type: string
        description: "String identifying the toolchain: '${os}-${compiler}-${compilerVersion}' (ex: linux-gcc-13)"
        required: true
      build_type:
        type: string
        description: "Build type (Debug/Release)"
        required: true


env:
  conan_pr_host: "./.github/conanProfiles/${{ inputs.toolchain_id }}.txt"
  drMemory_base: '$HOME/drMemory'
  vcpkg_base: '$HOME/vcpkg'

jobs:
  ci_run:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4

      - id: build_type
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ inputs.build_type }}

      - name: "[setup] Enable MSVC"
        if: ${{ contains(inputs.toolchain_id, 'msvc') }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: "[setup] Install vcpkg"
        run: python '.github/scripts/installVcpkg.py' --dest "${{ env.vcpkg_base }}"

      - name: "[setup] Install Apt packages & C++ compiler (ubuntu)"
        if: ${{ contains(inputs.runner, 'ubuntu') }}
        run: python '.github/scripts/ubuntu/installAptPackages.py' --toolchainId "${{ inputs.toolchain_id }}"

      #- name: "[setup] Install DrMemory (windows)"
      #  if: ${{ contains(inputs.runner, 'windows') }}
      #  run: python '.github/scripts/msvc/installDrMemory.py' --dest "${{ env.drMemory_base }}"

      - name: "[setup] Install conan"
        run: |
          pipx install conan
          pipx ensurepath
          conan profile detect

      - name: "[setup] Cache conan packages"
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p
          key: conan-cache-${{ inputs.toolchain_id }}-${{ steps.build_type.outputs.lowercase }}

      - name: "[build] conan install"
        run: conan install . -pr:h=${{ env.conan_pr_host }} -s:h build_type=${{ inputs.build_type }} --build=missing

      - name: "[build] cmake config (windows)"
        if: ${{ contains(inputs.runner, 'windows') }}
        run: >
          cmake . --preset conan-default
          -D "GUSTAVE_ENABLE_MEMCHECK_TESTS=OFF"
          -D "GUSTAVE_CONAN_HOST_PROFILE=${{ env.conan_pr_host }}"
          -D "GUSTAVE_VCPKG_ROOT=${{ env.vcpkg_base }}"

      - name: "[build] cmake config (ubuntu)"
        if: ${{ contains(inputs.runner, 'ubuntu') }}
        run: >
          cmake . --preset conan-default
          -D "GUSTAVE_CONAN_HOST_PROFILE=${{ env.conan_pr_host }}"
          -D "GUSTAVE_VCPKG_ROOT=${{ env.vcpkg_base }}"

      - name: "[build/setup] Install Python venvs"
        run: cmake --build --preset conan-${{ steps.build_type.outputs.lowercase }} --target venvs

      - name: "[build] Build"
        run: cmake --build --preset conan-${{ steps.build_type.outputs.lowercase }}

      - name: "[build] Run unit tests"
        run: cmake --build --preset conan-${{ steps.build_type.outputs.lowercase }} --target run-unit-tests

      - name: "[build] Run tool tests"
        run: cmake --build --preset conan-${{ steps.build_type.outputs.lowercase }} --target run-tool-tests

      - name: "[build] Run memcheck tests"
        # Disabled drMemory test (windows) because of too many false positives
        if: ${{ contains(inputs.runner, 'ubuntu') }}
        run: cmake --build --preset conan-${{ steps.build_type.outputs.lowercase }} --target run-memcheck-tests

      - name: "[build] Run tutorials"
        run: cmake --build --preset conan-${{ steps.build_type.outputs.lowercase }} --target run-tutorials

      - name: "[build] Run packaging tests"
        run: cmake --build --preset conan-${{ steps.build_type.outputs.lowercase }} --target run-packaging-tests
