---

name: Windows VS-2022

on: [push, pull_request, workflow_dispatch]

jobs:
  windows_msvc193:
    uses: ./.github/workflows/CI-common.yml
    with:
      runner: windows-2022
      conan_pr_host: ./.github/conanProfiles/windows-msvc193.txt
      toolchain_id: windows-msvc-193
