---

name: Linux clang-17

on: [push, pull_request]

jobs:
  skip_duplicate:
    runs-on: ubuntu-24.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          skip_after_successful_duplicate: true

  linux_clang17:
    runs-on: ubuntu-24.04
    needs: skip_duplicate
    if: needs.skip_duplicate.outputs.should_skip != 'true'
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: "[setup] Install apt-get packages"
        run: |
          sudo apt update
          sudo apt install -y ninja-build libc++-17-dev

      - name: "[setup] Install conan"
        run: |
          pipx install conan
          pipx ensurepath

      - name: "[setup] Cache conan packages"
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p
          key: conan-linux-clang17-release

      - name: "[build] conan install"
        run: conan install . -pr:b=./.github/conanProfiles/ubuntu24.txt -pr:h=./.github/conanProfiles/linux-clang17.txt -s:h build_type=Release --build=missing

      - name: "[build] cmake config"
        run: cmake . --preset conan-x86_64-linux-clang-17

      - name: "[build] Build"
        run: cmake --build . --preset conan-x86_64-linux-clang-17-release

      - name: "[build] Run unit tests"
        run: cmake --build . --preset conan-x86_64-linux-clang-17-release --target run-tests
