---

name: Linux clang-17

on:
  workflow_call:
    inputs:
      should_skip:
        description: 'Indicates if the workflow must be run'
        default: 'true'
        required: false
        type: string

env:
  cmake_profile: conan-x86_64-linux-clang-17
  conan_pr_build: ./.github/conanProfiles/ubuntu24.txt
  conan_pr_host: ./.github/conanProfiles/linux-clang17.txt

jobs:
  linux_clang17:
    runs-on: ubuntu-24.04
    if: inputs.should_skip != 'true'
    strategy:
      matrix:
        build_type: [Debug, Release]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - id: build_type
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ matrix.build_type }}

      - name: "[setup] Install apt-get packages"
        run: |
          sudo apt update
          sudo apt install -y ninja-build libc++-17-dev valgrind

      - name: "[setup] Install conan"
        run: |
          pipx install conan
          pipx ensurepath

      - name: "[setup] Cache conan packages"
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p
          key: ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }}

      - name: "[build] conan install"
        run: conan install . -pr:b=${{ env.conan_pr_build }} -pr:h=${{ env.conan_pr_host }} -s:h build_type=${{ matrix.build_type }} --build=missing

      - name: "[build] cmake config"
        run: >
          cmake . --preset ${{ env.cmake_profile }}
          -D "GUSTAVE_CONAN_BUILD_PROFILE=${{ env.conan_pr_build }}"
          -D "GUSTAVE_CONAN_HOST_PROFILE=${{ env.conan_pr_host }}"

      - name: "[build] Build"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }}

      - name: "[build] Run unit tests"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-unit-tests

      - name: "[build] Run tool tests"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-tool-tests

      - name: "[build] Run memcheck tests"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-memcheck-tests

      - name: "[build] Run packaging tests"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-packaging-tests
