---

name: Windows VS-2022

on:
  workflow_call:
    inputs:
      should_skip:
        description: 'Indicates if the workflow must be run'
        default: 'true'
        required: false
        type: string

env:
  cmake_profile: conan-x86_64-windows-msvc-193

jobs:
  windows_msvc193:
    runs-on: windows-2022
    if: inputs.should_skip != 'true'
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v4

      - id: build_type
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ matrix.build_type }}

      - uses: ilammy/msvc-dev-cmd@v1

      - name: "[setup] Install conan"
        run: |
          pipx install conan
          pipx ensurepath

      - name: "[setup] Cache conan packages"
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p
          key: ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }}

      - name: "[build] conan install"
        run: conan install . -pr:b=./.github/conanProfiles/windows2022.txt -pr:h=./.github/conanProfiles/windows-msvc193.txt -s:h build_type=${{ matrix.build_type }} --build=missing

      - name: "[build] cmake config"
        run: cmake . --preset ${{ env.cmake_profile }}

      - name: "[build] Build"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }}

      - name: "[build] Run unit tests"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-tests

      - name: "[build] Run tool tests"
        run: cmake --build --preset ${{ env.cmake_profile }}-${{ steps.build_type.outputs.lowercase }} --target run-tool-tests
